name: social_login_app
description: A Flutter mobile app for social media login with CAPTCHA
version: test1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter_facebook_auth: ^6.0.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  g_recaptcha_v3: ^0.0.5
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/